### PR TITLE
Issue#27Corrected the overlapping issue of section 3 on section 2 by decreasing the viewport height.

### LINKED ISSUE #27: section3 image overlaps section2 feature illustrations
On half-width window on desktop, it seems that section3 overlays section2:

image

Any idea what's causing this?

### PR DESCRIPTION
**Pull request by nathanbiller**
Fixes #27

### CODE REVIEW

**Comment by StefMa** [comment]
Sry for the noise and thank you for this PR @nathanbiller.

I rebased this PR so the commit history is different now, sry for this.
But I wanted to fix my CI 🙃 .

Anyway/
This PR is now deployed to https://hugo-fresh-pull-76.now.sh
Unfortunately I still notice the issue.

**Comment by nathanbiller** [comment]
Hmm, sorry about that @StefMa It's odd because it still seems to work locally on my copy. How confident are you that the site has this PR pushed? When I look at the styles with Chrome's Inspect tool I seeing that img.pushed-image style still set to -29vh. And when I manually override it to -8vh it seems to work correctly.

Screenshot 2019-09-25 09 11 16

**Comment by StefMa** [comment]
Hmm.. your are right. The publishing seems still wrong >.<.
I try to do this automatically by circleci.
You can checkout the config [here](https://github.com/StefMa/hugo-fresh/blob/master/.circleci/config.yml).

**Comment by nathanbiller** [comment]
I love the idea of a continuous integration testing tool, but I'm not very familiar with them, so understanding that config file right now is a bit beyond my abilities :( I'm not sure if this walkthrough might help? https://forestry.io/blog/automate-deploy-w-circle-ci/

**Comment by StefMa** [comment]
It seems that the deployment isn't updated correctly.
I wanted to update now but I'm searching for binaries :D. See https://github.com/zeit/now/issues/3074

**Comment by StefMa** [comment]
Um, well. That is pretty strange.

Even if the files are the new ones they hugo creates somehow the stuff with the old config 😕 
Checkout [this build](https://circleci.com/gh/StefMa/hugo-fresh/103).

The output from the "tab" create hugo site is first:
Bildschirmfoto 2019-10-02 um 11 49 21
then I create the site with `hugo` and the css will be generated with the 29 value... 😠 
Bildschirmfoto 2019-10-02 um 11 49 45

**Comment by nathanbiller** [comment]
@StefMa What version of hugo are you using on your local machine? Can you confirm that this happens when you run the site locally on your computer? It works for me perfectly both on my local computer and on my deployed site.

Based on the config that you linked to the test is using a rather old version of hugo `Installing hugo (0.46-r0)`

Asset post-processing _should_ have been added as of 0.43, but it's possible there were bugs. When I do a build on v0.55.6 v0.56.0 or v0.58.2 it correctly compiles a cache-busting "style.min.<xxx>.css" in my public/css folder. I'm guessing that the original creator may have generated that file manually because it wasn't originally possible for hugo to generate it at run time?

If you verify it works correctly using a more up-to-date version of hugo then you'd just need to update the build instructions for your test. I would suggest v0.55.6 because it's the last version that doesn't break single pages (until we're able to fix that issue) :)

**Comment by StefMa** [comment]
Finally. Its working. 
Thank you for the suggestions 👍 
I've updated the alpine distro which brings a newer hugo version..
I should change this to a fixed hugo version by downloading it from their releases page somehow.

**Pull request merged**
