### PR TITLE
fix: .Site.IsServer -> hugo.IsServer

### PR DESCRIPTION
**Pull request by ggrs**
.Site.IsServer is deprecated

### CODE REVIEW

**Comment by StefMa** [comment]
@ggrs why did you closed this?
I guess we can go with that 🙃

**Comment by dominiklanger** [comment]
@StefMa : Just run into the same problem... Results in an error with hugo v0.134. Could you implement the change suggested by ggrs's pull request (since he closed it) or shall I create a new pull request?

**Comment by StefMa** [comment]
@dominiklanger i just created #218. But it seems that is a breaking change...
Do you know with which version Hugo introduced hugo.IsServer?

**Comment by StefMa** [comment]
Or another question..
Is .Site.IsServer removed now? Or still just an deprecation?

**Comment by dominiklanger** [comment]
@StefMa 
- _hugo.IsServer_ has been introduced with v0.120.0: https://gohugo.io/functions/hugo/isserver/
- _.Site.IsServer_ has been removed with v0.135.0.

**Comment by StefMa** [comment]
Here it says it is still available, no? 🤔

https://gohugo.io/methods/site/isserver/

**Comment by dominiklanger** [comment]
With Hugo v.0.134, I got the following ERROR message for the _hugo server_ command: 
```powershell
ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.135.0. Use hugo.IsServer instead.
``` 
I now upgraded to Hugo v.0.135, still get an error message, though slightly different:
```powershell
ERROR deprecated: .Site.IsServer was deprecated in Hugo v0.120.0 and will be removed in Hugo 0.136.0. Use hugo.IsServer instead.
``` 
An error is the third stage in their escalation of deprecation level: https://gohugo.io/troubleshooting/deprecation/

Would be great if the newest version in the MASTER branch runs without problems with the newest Hugo version.

**Comment by StefMa** [comment]
Thanks @dominiklanger !

I fixed it here #218 and a release is out with that. 
See https://github.com/StefMa/hugo-fresh/releases/tag/v1.2.0

Thanks for the follow-up help 🙏

**Pull request closed without merging**
