### PR TITLE
Added Open Graph Internal Template as an option for easy social sharing.

### PR DESCRIPTION
**Pull request by nathanbiller**

### CODE REVIEW

**Comment by StefMa** [comment]
What is "open graph"?
Can you please give a short explanation whit it does and what it will change if enabled?

**Comment by nathanbiller** [comment]
Sure: Open Graph was introduced in 2010 by Facebook which allows content to enable rich "graph" objects which FB can easily integrate with. So if you try to share a default page from our template now on FB you might get a blank image or the text it shares or the preview might be incorrect. This internal template basically adds a few meta properties like "og:title" which FB can connect and interpret.

In single page front matter, you can specify a `description:` or` image:` which any social website that uses the social graph (primarily FB) will correctly interpret that data and display what the content provider wants. Because I set it up as an optional variable it changes nothing for those that don't enable it. You must explicitly state that you want to have it included, otherwise this modification is entirely ignored. I debated whether to just always include it because who wouldn't want to make their website easier to share, but ultimately chose to make it an optional feature because it does add a few additional lines of codes to each page.

This was a recommendation made to me by my UX designer; otherwise, I wouldn't have even thought about it. Here are more details: https://neilpatel.com/blog/open-graph-meta-tags/

**Comment by nathanbiller** [comment]
This was a recommendation made to me by my UX designer; otherwise, I wouldn't have even thought about it.

**Comment by StefMa** [comment]
Thank you. Sounds cool 👍

**Pull request merged**
