### PR TITLE
Added the ability to use google analytics using Hugo's internal templ…

### PR DESCRIPTION
**Pull request by nathanbiller**
…ate. Added a sample config and instructions to config.yaml for the example site and added in a link for the google analytics internal template for the navbar partial per https://gohugo.io/templates/internal/

### CODE REVIEW

**Comment by lucperkins** [comment]
This should be somewhere in the `<head>` component, not in the navbar

**Comment by nathanbiller** [comment]
Thanks for your feedback @lucperkins Makes complete sense. The only other theme I've worked on had a "head.html" partial, but hugo-fresh doesn't. Should I create a new partial just for this snippet of code or is there an existing one that I'm overlooking that would make sense?

**Comment by lucperkins** [comment]
The meta partial

**Comment by nathanbiller** [comment]
Corrected as advised @lucperkins :) Thanks!

**Comment by StefMa** [comment]
What happen if I don't want to use this feature and don't setup the
configuration?
Do I get errors?

**Comment by nathanbiller** [comment]
Good question @StefMa Everything compiled correctly when you either leave the "googleAnalytics:" param out completely or leave it blank. I had considered writing Go Code that would only put that in if the param existed, but after testing and noticing that the html source code generated didn't change before I put this in or after if left blank I reasoned that whatever internal template the Hugo team built fails elegantly when not provided with a variable.

**Comment by StefMa** [comment]
Thank you @nathanbiller!

**Pull request merged**
