### PR TITLE
Drop CircleCI, add link checker

### PR DESCRIPTION
**Pull request by deining**
This PR bumps versions inside the GitHub deploy action. It also fixes a typo and renames `config.yaml` to `hugo.yaml` in the exampleSite.

### CODE REVIEW

**Comment by deining** [comment]
I just realized, that the CI run is failing now. :cry:.
I had a look at the CircleCIs `config.yml` and found that hugo must be bumped to latest version 0.110.0 (only this version works with `hugo.yaml`). I tried to do, so, but build is still failing, due to reasons I don't understand. @StefMa: can you step in here, please?

**Note**: I realized that you are using `sed` to change the baseURL inside `config.yaml`. What about using hugo's `baseURL` parameter on site build? Wouldn't that allow to drop the sed part altogether?

**Comment by StefMa** [comment]
Hey @deining,
thanks for taking care! Really appreciate it.

I think its time to move to GH Actions completely and get rid of CircleCI...
I added CircleCI before GH Actions were available.

Nowadays we have all the tools (actions) available to make this process way smother...

If you like you can migrate to GH Actions here. Otherwise I will do it in the next days...
Let me know what do you think 🙂

**Comment by deining** [comment]
> Hey @deining, thanks for taking care! Really appreciate it.

You are welcome!
 
> I think its time to move to GH Actions completely and get rid of CircleCI...

Wise decision!

> If you like you can migrate to GH Actions here.

I will give it a try right now!

**Comment by deining** [comment]
One additional question: I see that you site is hosted at vercel.com. Do you want to keep it there or do you want to move the site to GitHub pages? I will prepare as good as i can, but at a certain point, I will hand it over to you!

**Comment by deining** [comment]
I'm done here, handing over to you for finalization. Let me know if you run into trouble, good luck!

**Review by StefMa — APPROVED** [review]

**Comment by StefMa** [comment]
Well, I have no idea how to deploy to vercel on a pull request as it requires secrets... The `pull_request_target` should dot he job if I get it correctly but it didn't get triggered 😭 

Do you know how to make this possible @deining ? 

Otherwise I would go with another approach and save the hugo output as an github artifact...

**Comment by deining** [comment]
> Well, I have no idea how to deploy to vercel on a pull request as it requires secrets... The `pull_request_target` should dot he job if I get it correctly but it didn't get triggered 😭
> 
> Do you know how to make this possible @deining ?

My guess is that this is a problem with permissions.

grafik

The action is triggered from my repository, but I do not have write permissions to your repo (and I am not supposed to see your secrets either). This may be the reason why the action wrkflow is failing.

What I would propose:
- create a new branch `deploy_to_vercel` in your repo
- pull in my PR (from my branch [`deining:gh-action`](https://github.com/deining/hugo-fresh/tree/gh-action)) to this newly created branch
- make a pull request from your newly created `deploy_to_vercel` branch to your `master` branch.

Does this cure the problem?

**Review by StefMa — APPROVED** [review]
Let's give this a try 😅 
Thanks again @deining !

**Pull request merged**
